name: Syllabist Engine

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  Format:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31
        with:
          deno-version: v1.x

      - name: Run tests
        run: deno test --allow-all --coverage=cov_profile

      - name: Collect coverage
        run: deno coverage ./cov_profile --lcov > coverage.lcov

      - name: Upload coverage
        # You may pin to the exact commit or the version.
        # uses: codecov/codecov-action@c4cf8a4f03f0ac8585acb7c1b7ce3460ec15782f
        uses: codecov/codecov-action@v3.1.4
        with:
          # Repository upload token - get it from codecov.io. Required only for private repositories
          token: ${{ secrets.CODECOV_TOKEN }}

  Documentation:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1

      - name: Build documentation
        run: npx documentation build *.js --format html --output docs --project-name Syllabist-Engine

      - name: Setup Pages
        uses: actions/configure-pages@v3.0.6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: 'docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2.0.4

  Complete:  
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31
        with:
          deno-version: v1.x

      - name: Run Complete Workflow
        run: |
          cd e2e
          deno run --allow-all Workflows/Complete.js

  Compress-Expand:  
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
    
      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31
        with:
          deno-version: v1.x
    
      - name: Run Complete Workflow
        run: |
          cd e2e
          deno run --allow-all Workflows/Compress-Expand.js

  Transform-Compress:  
    runs-on: ubuntu-latest
        
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
        
      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31
        with:
          deno-version: v1.x
        
      - name: Run Complete Workflow
        run: |
          cd e2e
          deno run --allow-all Workflows/Transform-Compress.js

  Update-Separate:  
    runs-on: ubuntu-latest
            
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
            
      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31
        with:
          deno-version: v1.x
            
      - name: Run Complete Workflow
        run: |
          cd e2e
          deno run --allow-all Actions/Utility/Server.js &
          deno run --allow-all Workflows/Transform-Compress.js
