# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Syllabist Engine

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      - name: Run tests
        run: deno test --coverage=cov_profile

      - name: Collect coverage
        run: deno coverage ./cov_profile --lcov > coverage.lcov

      - name: Upload coverage
        # You may pin to the exact commit or the version.
        # uses: codecov/codecov-action@c4cf8a4f03f0ac8585acb7c1b7ce3460ec15782f
        uses: codecov/codecov-action@v3.1.4
        with:
          # Repository upload token - get it from codecov.io. Required only for private repositories
          token: ${{ secrets.CODECOV_TOKEN }}

  workflow:  
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      - name: Run Complete Workflow
        run: cd e2e && deno run --allow-read --allow-write Complete.js
