name: Syllabist Engine

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["*"]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  Format:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755

      - name: Run formatter
        run: dx oxfmt --check

      - name: Run linter
        run: dx oxlint

  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755

      - name: Run tests
        run: deno test --allow-all --coverage --junit-path=junit.xml

      - name: Upload coverage
        uses: codecov/codecov-action@b203f00e21e8678aa5d26b967170503dbb855a18
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@983465b8d8414906a3ad05612a640f1d1e770028
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  Complete:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755

      - name: Run Workflow
        run: |
          cd e2e
          deno run --allow-all Workflows/Complete.js

  Compress:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755

      - name: Run Workflow
        run: |
          cd e2e
          deno run --allow-all Workflows/Compress.js

  Expand:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755

      - name: Run Workflow
        run: |
          cd e2e
          deno run --allow-all Workflows/Expand.js

  Separate:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755

      - name: Run Workflow
        run: |
          cd e2e
          deno run --allow-all Workflows/Separate.js

  Transform:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755

      - name: Run Workflow
        run: |
          cd e2e
          deno run --allow-all Workflows/Transform.js

  # Update:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Setup repo
  #       uses: actions/checkout@v4

  #     - name: Setup Deno
  #       uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755

  #     - name: Run Workflow
  #       run: |
  #         cd e2e
  #         deno run --allow-all Workflows/Update.js
